### PR TITLE
make some fields an enum instead of a struct

### PR DESCRIPTION
**Pull request by johannesvollmer**

### CODE REVIEW

**Comment by johannesvollmer** [comment]
`mem::size_of::<Update>()` went from `30,384` to `5,384` bytes

**Review by EdJoPaTo — APPROVED** [review]
Besides the missing `cargo fmt` it looks good.

I think we can also remove the TypedBuilder from the Update (and maybe other types) as its a simple object now. But we should do that in a separate PR to keep things simple.

**Review by ayrat555 — APPROVED** [review]
LGTM

**Comment by ayrat555** [comment]
released in 0.14.0

**Pull request merged**
