### PR TITLE
Bot API 7.0

### PR DESCRIPTION
**Pull request by ayrat555**

### CODE REVIEW

**Review by EdJoPaTo — APPROVED** [review]
Only looked into the file changes which seem fine and not the documentation. Also haven't tried if they actually work.

**Comment by Programistich** [comment]
Idk, but available_reaction return None all direct messages and group (in settings all reactions ON)

**Comment by ayrat555** [comment]
@Programistich 

it's returned only in [getChat](https://core.telegram.org/bots/api#getchat).

```rust
 Ok(MethodResponse { ok: true, result: Chat { id: -4072265349, type_field: Group, title: Some("test"), username: None, first_name: None, last_name: None, is_forum: None, photo: None, active_usernames: None, available_reactions: Some([Emoji(ReactionTypeEmoji { emoji: "👍" }), Emoji(ReactionTypeEmoji { emoji: "👎" })]), emoji_status_custom_emoji_id: None, emoji_status_expiration_date: None, bio: None, has_private_forwards: None, has_restricted_voice_and_video_messages: None, join_to_send_messages: None, join_by_request: None, description: None, invite_link: Some("https://t.me/+NuBgd-Qu8IFiMjRi"), pinned_message: None, permissions: Some(ChatPermissions { can_send_messages: Some(true), can_send_audios: Some(true), can_send_documents: Some(true), can_send_photos: Some(true), can_send_videos: Some(true), can_send_video_notes: Some(true), can_send_voice_notes: Some(true), can_send_polls: Some(true), can_send_other_messages: Some(true), can_add_web_page_previews: Some(true), can_change_info: Some(true), can_invite_users: Some(true), can_pin_messages: Some(true), can_manage_topics: Some(true) }), slow_mode_delay: None, message_auto_delete_time: None, has_aggressive_anti_spam_enabled: None, has_hidden_members: None, has_protected_content: None, sticker_set_name: None, can_set_sticker_set: None, linked_chat_id: None, location: None }, description: None })
```

**Comment by Programistich** [comment]
@ayrat555 

IDK, but api return 

`Ok(MethodResponse { ok: true, result: true, description: None })`

send_react(&api, &message,  "👍").await;

```
async fn send_react(api: &AsyncApi, message: &Message, reaction: &str)  {
    let reaction = ReactionTypeEmoji { emoji: String::from(reaction) };
    let reaction_type = ReactionType::Emoji(reaction);

    let send_react_params = SetMessageReactionParams::builder()
        .chat_id(message.chat.id)
        .message_id(message.message_id)
        .reacion(vec![reaction_type])
        .is_big(true)
        .build();

    let result = api.set_message_reaction(&send_react_params).await;
    println!("{:?}", result);
}
```


But in telegram none reactions and etc

**Comment by ayrat555** [comment]
@Programistich thank you. the bug is found and fixed in this branch

**Pull request merged**
